### ISSUE TITLE
Unhandled Exception: System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by evan** [goncalopereira/statsd-csharp-client#33]
The following fatal exception occurs in our app:

    Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
      at System.Collections.Generic.List`1.Add(T item)
      at StatsdClient.Statsd.Add[TCommandType](String name, Double value)
    ...

I believe this may be a thread safety issue. Is access to the Commands List thread safe?

**Comment by DarrellMozingo** [comment]
Just pushed this in 1.0.0.17. Let me know if you have any problems.
