### ISSUE TITLE
Nuget package 1.0.0.16 is missing sampleRate for MetricsTimer

### ISSUE THREAD

**Issue by chrismwendt** [goncalopereira/statsd-csharp-client#37]
Although the version bump to 1.0.0.16 was committed after commit 2c098139e09db7cb0c0a1185530bc384ba8750ba, the Nuget package 1.0.0.16 does not contain the changes from that commit.

Any idea what's going on?

**Comment by DarrellMozingo** [comment]
Not really sure Chris, but there's been some code cleanup after that bump anyway so I'll repush to nuget after a pending pull request is taken care of here soon.

**Comment by DarrellMozingo** [comment]
Just pushed version 1.0.0.17 which should include the change. Let me know if you have any problems.
