### ISSUE TITLE
Support for Async

### ISSUE THREAD

**Issue by niemyjski** [goncalopereira/statsd-csharp-client#39]
Are there any plans for Async support?

**Comment by DarrellMozingo** [comment]
Not currently. What ideas do you have? As it sends UDP packets it's a very small performance impact already (doesn't make a full TCP connection w/handshake, resend, etc).

**Comment by niemyjski** [comment]
Yeah I can see your point. I just figured it might help future proof the client in the case you wanted to also support tcp. Also some of the socket methods support async.

**Comment by DarrellMozingo** [comment]
Very true. I'd rather introduce it as and when needed, even if that means making overloads. Thanks for the suggestion though!
