### ISSUE TITLE
Is string.Format really needed?

### ISSUE THREAD

**Issue by MichaelLogutov** [goncalopereira/statsd-csharp-client#41]
I know this maybe preventive optimization, but is string.Format in GetCommand really needed? Maybe simple string.Concat will suffice?

**Comment by DarrellMozingo** [comment]
Honestly it's just the way it was coded up. I think `string.Format` would read better than `string.Concat` here too. Are you thinking about it from a performance standpoint?

**Comment by MichaelLogutov** [comment]
Yeah,  mostly. Since StatsD usually used as fast telemetry service I thought that using string.Format parsing for concatenation of string is a bit overkill.

**Comment by DarrellMozingo** [comment]
I can't imagine it having too big of a difference, but you're quite right it should be as quick as possible. If you'd like to submit a PR I'll happily merge it in. Thanks!

**Comment by MichaelLogutov** [comment]
Yeah, will do when I get back from holidays.
