### ISSUE TITLE
Gauge misses overload to send Δ values

### ISSUE THREAD

**Issue by crunchie84** [goncalopereira/statsd-csharp-client#44]
The [gauge specification by Etsy](https://github.com/etsy/statsd/blob/master/docs/metric_types.md#gauges) allows for sending updates to the current gauge value by prepending the value submitted with an explicit '+' or '-'.

Unfortunately, this functionality is missing from this statsd client. Adding an optional argument (`isDelta=false`) to the Gauge function would not break behaviour of existing users but allow for this usecase.

**Comment by Ei8htSe7en** [comment]
Almost opened my own issue and saw someone already beat me to it! Any updates on this issue? I am starting to use StatsD more and hit a strong use case for a Gauge with Delta values.

@crunchie84  - Were you planning on putting in a PR for this?

**Comment by crunchie84** [comment]
Hey @josheinhorn i've got the code implemented but didn't have time to field-test it tonight. After that is done i will create a PR for this issue. 

if you are curious the changes are here: https://github.com/crunchie84/statsd-csharp-client/tree/feature/gauge-delta-values

**Comment by josheinhorn** [comment]
@crunchie84 Very cool &mdash; I basically did the same thing in my fork, except I also added an `Add` method since my system relies on batching metrics together (as well as `async` support and TCP support)

**Comment by DarrellMozingo** [comment]
Perfect timing, I was just about to do this myself :) Was on holiday but taking a look at the PR right now!

**Comment by DarrellMozingo** [comment]
BTW, just pushed this to NuGet (with a few other changes I'd been meaning to make): 

https://www.nuget.org/packages/StatsdClient/1.1.0

Thanks again!
